import "dotenv/config";
import { prisma } from "../src/lib/prisma";

const clients = [
  {
    firstName: "Juan",
    lastName: "González Pérez",
    email: "juan.gonzalez@email.com",
    phone: "+56 9 8765 4321",
    rut: "12.345.678-9",
    passportNumber: "AB123456",
    passportExpiry: "2027-08-15",
    passportIssueDate: "2017-08-15",
    passportCountry: "Chile",
    birthDate: "1980-05-20",
    nationality: "Chileno",
    address: "Calle Los Leones 456, Santiago",
    frequentFlyerNumbers: ["AA1234567", "UA9876543"],
    restrictions: "Vegetariano, sin nueces",
    referralSource: "REFERRAL",
    bankAccount: "123456789",
    bankName: "Banco de Chile",
    bankAccountHolder: "Juan González Pérez",
    bankEmail: "juan.gonzalez@email.com",
    isActive: true,
  },
  {
    firstName: "María",
    lastName: "López Rodríguez",
    email: "maria.lopez@email.com",
    phone: "+56 9 8765 4322",
    rut: "13.456.789-0",
    passportNumber: "CD987654",
    passportExpiry: "2026-12-10",
    passportIssueDate: "2016-12-10",
    passportCountry: "Chile",
    birthDate: "1985-03-15",
    nationality: "Chilena",
    address: "Av. Providencia 789, Santiago",
    frequentFlyerNumbers: ["LH5654321"],
    restrictions: "Diábetica, sin azúcares",
    referralSource: "WEBSITE",
    bankAccount: "987654321",
    bankName: "Banco Santander",
    bankAccountHolder: "María López Rodríguez",
    bankEmail: "maria.lopez@email.com",
    isActive: true,
  },
  {
    firstName: "Carlos",
    lastName: "Martínez Silva",
    email: "carlos.martinez@email.com",
    phone: "+56 9 8765 4323",
    rut: "14.567.890-1",
    passportNumber: "EF456789",
    passportExpiry: "2028-01-20",
    passportIssueDate: "2018-01-20",
    passportCountry: "Chile",
    birthDate: "1975-07-30",
    nationality: "Chileno",
    address: "Calle Merced 321, Valparaíso",
    frequentFlyerNumbers: ["QF7654321", "BA1234567"],
    restrictions: "Gluten-free",
    referralSource: "CONSULATE",
    bankAccount: "555666777",
    bankName: "BCI",
    bankAccountHolder: "Carlos Martínez Silva",
    bankEmail: "carlos.martinez@email.com",
    isActive: true,
  },
  {
    firstName: "Andrea",
    lastName: "Fernández García",
    email: "andrea.fernandez@email.com",
    phone: "+56 9 8765 4324",
    rut: "15.678.901-2",
    passportNumber: "GH234567",
    passportExpiry: "2025-06-05",
    passportIssueDate: "2015-06-05",
    passportCountry: "Argentina",
    birthDate: "1990-11-12",
    nationality: "Argentina",
    address: "Calle Serrano 654, Concepción",
    frequentFlyerNumbers: ["AR9876543"],
    restrictions: "Alérgica a mariscos",
    referralSource: "REFERRAL",
    bankAccount: "111222333",
    bankName: "Itaú",
    bankAccountHolder: "Andrea Fernández García",
    bankEmail: "andrea.fernandez@email.com",
    isActive: true,
  },
  {
    firstName: "Roberto",
    lastName: "Vargas Delgado",
    email: "roberto.vargas@email.com",
    phone: "+56 9 8765 4325",
    rut: "16.789.012-3",
    passportNumber: "IJ345678",
    passportExpiry: "2029-03-18",
    passportIssueDate: "2019-03-18",
    passportCountry: "Perú",
    birthDate: "1982-09-05",
    nationality: "Peruano",
    address: "Av. Costanera 234, Puerto Montt",
    frequentFlyerNumbers: ["LA8765432"],
    restrictions: "Hipertensión, bajo en sodio",
    referralSource: "OTHER",
    bankAccount: "444555666",
    bankName: "Banco Estado",
    bankAccountHolder: "Roberto Vargas Delgado",
    bankEmail: "roberto.vargas@email.com",
    isActive: true,
  },
  {
    firstName: "Patricia",
    lastName: "Morales Ruiz",
    email: "patricia.morales@email.com",
    phone: "+56 9 8765 4326",
    rut: "17.890.123-4",
    passportNumber: "KL567890",
    passportExpiry: "2026-09-22",
    passportIssueDate: "2016-09-22",
    passportCountry: "Colombia",
    birthDate: "1988-01-28",
    nationality: "Colombiana",
    address: "Calle Independencia 876, Temuco",
    frequentFlyerNumbers: ["AV7654321", "AC1234567"],
    restrictions: "Sin lácteos",
    referralSource: "WEBSITE",
    bankAccount: "777888999",
    bankName: "Banco Falabella",
    bankAccountHolder: "Patricia Morales Ruiz",
    bankEmail: "patricia.morales@email.com",
    isActive: true,
  },
  {
    firstName: "Fernando",
    lastName: "Jiménez Cortés",
    email: "fernando.jimenez@email.com",
    phone: "+56 9 8765 4327",
    rut: "18.901.234-5",
    passportNumber: "MN789012",
    passportExpiry: "2027-11-08",
    passportIssueDate: "2017-11-08",
    passportCountry: "Bolivia",
    birthDate: "1972-04-10",
    nationality: "Boliviano",
    address: "Calle Manuel Rodríguez 432, Valdivia",
    frequentFlyerNumbers: ["BO9876543"],
    restrictions: "Alérgico a antibióticos",
    referralSource: "CONSULATE",
    bankAccount: "222333444",
    bankName: "Scotiabank",
    bankAccountHolder: "Fernando Jiménez Cortés",
    bankEmail: "fernando.jimenez@email.com",
    isActive: true,
  },
  {
    firstName: "Claudia",
    lastName: "Navarro Soto",
    email: "claudia.navarro@email.com",
    phone: "+56 9 8765 4328",
    rut: "19.012.345-6",
    passportNumber: "OP234567",
    passportExpiry: "2024-07-14",
    passportIssueDate: "2014-07-14",
    passportCountry: "Ecuador",
    birthDate: "1995-06-22",
    nationality: "Ecuatoriana",
    address: "Av. Libertad 123, Puerto Varas",
    frequentFlyerNumbers: ["LATAM123456"],
    restrictions: "Asma, llevar inhalador",
    referralSource: "REFERRAL",
    bankAccount: "666777888",
    bankName: "HSBC",
    bankAccountHolder: "Claudia Navarro Soto",
    bankEmail: "claudia.navarro@email.com",
    isActive: true,
  },
  {
    firstName: "Diego",
    lastName: "Araya Flores",
    email: "diego.araya@email.com",
    phone: "+56 9 8765 4329",
    rut: "20.123.456-7",
    passportNumber: "QR456789",
    passportExpiry: "2028-05-30",
    passportIssueDate: "2018-05-30",
    passportCountry: "Uruguay",
    birthDate: "1986-02-14",
    nationality: "Uruguayo",
    address: "Calle O'Higgins 567, Osorno",
    frequentFlyerNumbers: ["UY8765432"],
    restrictions: "Ninguna",
    referralSource: "WEBSITE",
    bankAccount: "999888777",
    bankName: "Mufg Bank",
    bankAccountHolder: "Diego Araya Flores",
    bankEmail: "diego.araya@email.com",
    isActive: true,
  },
  {
    firstName: "Lorena",
    lastName: "Castillo Miranda",
    email: "lorena.castillo@email.com",
    phone: "+56 9 8765 4330",
    rut: "21.234.567-8",
    passportNumber: "ST321098",
    passportExpiry: "2025-10-12",
    passportIssueDate: "2015-10-12",
    passportCountry: "Venezuela",
    birthDate: "1993-10-09",
    nationality: "Venezolana",
    address: "Calle Carrera 234, La Serena",
    frequentFlyerNumbers: ["VB7654321"],
    restrictions: "Presión alta, bajo estrés",
    referralSource: "OTHER",
    bankAccount: "333444555",
    bankName: "Banco de Crédito",
    bankAccountHolder: "Lorena Castillo Miranda",
    bankEmail: "lorena.castillo@email.com",
    isActive: true,
  },
];

async function main() {
  console.log("🌱 Iniciando seed de clientes...");

  for (const client of clients) {
    const existingClient = await prisma.client.findFirst({
      where: { rut: client.rut },
    });

    if (existingClient) {
      console.log(
        `✓ Cliente ya existe: ${client.firstName} ${client.lastName} (RUT: ${client.rut})`
      );
      continue;
    }

    const created = await prisma.client.create({
      data: {
        ...client,
      },
    });

    console.log(
      `✅ Cliente creado: ${created.firstName} ${created.lastName} (ID: ${created.id})`
    );
  }

  console.log("🎉 Seed de clientes completado");
}

main()
  .catch((error) => {
    console.error("❌ Error durante seed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
