// 1. Definimos todas las acciones posibles en el sistema
export const PERMISSIONS = {
  // Usuarios
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_USERS: "VIEW_USERS",
  
  // Configuraciones Globales
  MANAGE_SYSTEM_CONFIG: "MANAGE_SYSTEM_CONFIG",
  
  // Clientes
  CREATE_CLIENT: "CREATE_CLIENT",
  VIEW_CLIENTS: "VIEW_CLIENTS",
  DELETE_CLIENT: "DELETE_CLIENT",

  // Solicitudes (Requests)
  VIEW_REQUESTS: "VIEW_REQUESTS",
  MANAGE_REQUESTS: "MANAGE_REQUESTS",
  DELETE_REQUEST: "DELETE_REQUEST",

  // Cotizaciones
  VIEW_QUOTATIONS: "VIEW_QUOTATIONS",
  MANAGE_QUOTATIONS: "MANAGE_QUOTATIONS",
  DELETE_QUOTATION: "DELETE_QUOTATION",

  // Pagos
  VIEW_PAYMENTS: "VIEW_PAYMENTS",
  MANAGE_PAYMENTS: "MANAGE_PAYMENTS",
  DELETE_PAYMENT: "DELETE_PAYMENT",

  // Proveedores (Vouchers)
  VIEW_PROVIDERS: "VIEW_PROVIDERS",
  MANAGE_PROVIDERS: "MANAGE_PROVIDERS",
  DELETE_PROVIDER: "DELETE_PROVIDER",

  // Vouchers
  VIEW_VOUCHERS: "VIEW_VOUCHERS",
  MANAGE_VOUCHERS: "MANAGE_VOUCHERS",
  DELETE_VOUCHER: "DELETE_VOUCHER",

  // Reportes
  VIEW_REPORTS: "VIEW_REPORTS",

  // Bitácora / Logs
  VIEW_LOGS: "VIEW_LOGS",
  PURGE_LOGS: "PURGE_LOGS", // Crítico, solo para Administradores de Sistema

  // Plantillas de Correo
  VIEW_TEMPLATES: "VIEW_TEMPLATES",
  MANAGE_TEMPLATES: "MANAGE_TEMPLATES",
  DELETE_TEMPLATE: "DELETE_TEMPLATE",

  // Envío de correos de cumpleaños
  SEND_BIRTHDAY_EMAILS: "SEND_BIRTHDAY_EMAILS",

  //Confirmaciones
  VIEW_CONFIRMED_REQUESTS: "VIEW_CONFIRMED_REQUESTS",


} as const;

export type Permission = keyof typeof PERMISSIONS;

// 2. Asignamos los permisos a cada Rol de la Agencia
export const AGENCY_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  GERENTE: [
   PERMISSIONS.MANAGE_USERS, PERMISSIONS.VIEW_USERS, 
    PERMISSIONS.MANAGE_SYSTEM_CONFIG,
    PERMISSIONS.SEND_BIRTHDAY_EMAILS,
    PERMISSIONS.CREATE_CLIENT, PERMISSIONS.VIEW_CLIENTS, PERMISSIONS.DELETE_CLIENT,
    PERMISSIONS.VIEW_REQUESTS, PERMISSIONS.MANAGE_REQUESTS, PERMISSIONS.DELETE_REQUEST,
    PERMISSIONS.VIEW_QUOTATIONS, PERMISSIONS.MANAGE_QUOTATIONS, PERMISSIONS.DELETE_QUOTATION,
    PERMISSIONS.VIEW_PAYMENTS, PERMISSIONS.MANAGE_PAYMENTS, PERMISSIONS.DELETE_PAYMENT,
    PERMISSIONS.VIEW_PROVIDERS, PERMISSIONS.MANAGE_PROVIDERS, PERMISSIONS.DELETE_PROVIDER,
    PERMISSIONS.VIEW_VOUCHERS, PERMISSIONS.MANAGE_VOUCHERS, PERMISSIONS.DELETE_VOUCHER,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.VIEW_TEMPLATES, PERMISSIONS.MANAGE_TEMPLATES, PERMISSIONS.DELETE_TEMPLATE
  ],
  FINANZAS: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_CLIENTS,
    PERMISSIONS.VIEW_REQUESTS,
    PERMISSIONS.VIEW_QUOTATIONS,
    PERMISSIONS.VIEW_PAYMENTS, PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.VIEW_PROVIDERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.SEND_BIRTHDAY_EMAILS,
  ],
  OPERACIONES: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_CLIENTS,
    PERMISSIONS.VIEW_REQUESTS,
    PERMISSIONS.VIEW_QUOTATIONS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.VIEW_PROVIDERS, PERMISSIONS.MANAGE_PROVIDERS,
    PERMISSIONS.VIEW_VOUCHERS, PERMISSIONS.MANAGE_VOUCHERS,
    PERMISSIONS.SEND_BIRTHDAY_EMAILS,
  ],
  AGENTE_VENTAS: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_CLIENT, PERMISSIONS.VIEW_CLIENTS,
    PERMISSIONS.VIEW_REQUESTS, PERMISSIONS.MANAGE_REQUESTS,
    PERMISSIONS.VIEW_QUOTATIONS, PERMISSIONS.MANAGE_QUOTATIONS,
    PERMISSIONS.VIEW_PAYMENTS, // Para ver si le pagaron su venta
    PERMISSIONS.VIEW_VOUCHERS, // Para descargar vouchers de sus clientes
    PERMISSIONS.SEND_BIRTHDAY_EMAILS,
  ],
};

// 3. Función evaluadora ultra-rápida
export function hasPermission(systemRole: string, agencyRole: string | null | undefined, permission: Permission): boolean {
  // El Súper Administrador siempre tiene acceso a todo
  if (systemRole === "ADMINISTRADOR") return true;
  
  // Si es un usuario normal, buscamos los permisos de su rol de agencia
  const agencyPerms = agencyRole ? AGENCY_ROLE_PERMISSIONS[agencyRole] || [] : [];
  return agencyPerms.includes(permission);
}